// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwmudcwknkyijiofemvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bXVkY3drbmt5aWppb2ZlbXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDgwNTMsImV4cCI6MjA2NzQ4NDA1M30.Lh9i9UO64diBZil_-8MP3HFC7zt9C5FU02Iqea8TXOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});