const data = [
  {
    title: "Slim Fit Jeans",
    description: "Comfortable and stylish jeans for men.",
    brand: "Levi's",
    gender: "Men",
    category: "Clothing",
    subcategory: "Jeans",
    price: 1999,
    discount: 15,
    rating: "4.3",
    theme: "Casual",
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    image: [
      "https://example.com/images/jeans1.jpg",
      "https://example.com/images/jeans2.jpg"
    ]
  },
  {
    title: "T-shirt",
    description: "Comfortable cotton t-shirt for men.",
    brand: "Nike",
    gender: "Men",
    category: "Clothing",
    subcategory: "T-Shirts",
    price: 999,
    discount: 20,
    rating: "4.5",
    subcategory: "T-Shirts",
    theme: "formal",
    size: ["M", "L", "XL"],
    color: ["White", "Black"],
    image: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400"]
  },
  {
    title: "T-Kids Graphic Tee",
    description: "Fun and colorful graphic tee for kids.",
    brand: "Puma",
    gender: "kid",
    price: 49.99,
    discount: 50,
    rating: "4.5",
    category: "Dresses",
    subcategory: "T-Shirts",
    theme: "formal",
    size: ["L", "M", "S"],
    color: ["Red", "Blue"],
    image: ["https://cdn.builder.io/api/v1/image/assets/70ad6d2d96f744648798836a6706b9db/195176e2222a7c41d44bd7662e7402d74c61a9a0?placeholderIfAbsent=true"]
  },
  {
    title: "Girls Summer Dress",
    description: "Stylish summer dress for girls.",
    brand: "Zara", 
    gender: "kid",
    price: 500,
    discount: 50,
    rating: "4.5",
    category: "topwear",
    subcategory: "Dresses",
    theme: "formal",
    size: ["L"],
    color: ["Pink", "Yellow"],
    image: ["https://cdn.builder.io/api/v1/image/assets/70ad6d2d96f744648798836a6706b9db/323635352eed4542ef83c5e9d41e0f884d43499e?placeholderIfAbsent=true"]
  },
  {
    title: "Girls Summer Dress",
    description: "Stylish summer dress for girls.",
    brand: "Zara",
    gender: "kid",
    price: 500,
    discount: 50,
    rating: "4.5",
    category: "topwear",
    subcategory: "Dresses",
    theme: "formal",
    size: ["L"],
    color: ["Pink", "Yellow"],
    image: ["https://cdn.builder.io/api/v1/image/assets/70ad6d2d96f744648798836a6706b9db/eb643d7fe0ae4338ccb6e5788c39e2bcd9311740?placeholderIfAbsent=true"]
  },
  {
    title: "Girls Summer Dress",
    description: "Stylish summer dress for girls.",
    brand: "Zara",
    gender: "kid",
    price: 500,
    discount: 50,
    rating: "4.5",
    category: "topwear",
    subcategory: "Dresses",
    theme: "formal",
    size: ["L"],
    color: ["Pink", "Yellow"],
    image: ["https://cdn.builder.io/api/v1/image/assets/70ad6d2d96f744648798836a6706b9db/1ae9ee2293ad29eef209760dacb27c2cfcc587ac?placeholderIfAbsent=true"]
  },
  {
    title: "T-shirt",
    description: "Comfortable cotton t-shirt for men.",
    brand: "Nike",
    gender: "Men",
    price: 499,
    discount: 30,
    rating: "4.5",
    category: "topwear",
    subcategory: "T-Shirts",
    theme: "casual",
    size: ["M", "L", "XL"],
    color: ["White", "Black"],
    image: ["https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=400"]
  },
  {
    title: "Dress",
    description: "Elegant evening dress for women.",
    brand: "Zara",
    gender: "Women",
    price: 1899,
    discount: 40,
    rating: "4.7",
    category: "ethnic",
    subcategory: "Dresses",
    theme: "party",
    size: ["S", "M", "L"],
    color: ["Red", "Black"],
    image: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400"]
  },
  {
    title: "Kurta",
    description: "Traditional kurta for women.",
    brand: "Zara",
    gender: "Women",
    price: 999,
    discount: 20,
    rating: "4.6",
    category: "ethnic",
    subcategory: "Kurtas",
    theme: "traditional",
    size: ["L"],
    color: ["Blue", "Green"],
    image: ["https://images.unsplash.com/photo-1521334884684-d80222895322?w=400"]
  },
  {
    title: "Jeans",
    description: "Stylish jeans for unisex.",
    brand: "Levi's",
    gender: "unisex",
    price: 1099,
    discount: 50,
    rating: "4.0",
    category: "bottomwear",
    subcategory: "Jeans",
    theme: "casual",
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    image: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=400"]
  },
  {
    title: "Jeans",
    description: "Stylish jeans for men.",
    brand: "Levi's",
    gender: "Men",
    price: 899,
    discount: 35,
    rating: "4.3",
    category: "bottomwear",
    subcategory: "Jeans",
    theme: "casual",
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    image: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=400"]
  },
  {
    title: "Shirt",
    description: "Comfortable cotton shirt for men.",
    brand: "Nike",
    gender: "Men",
    price: 799,
    discount: 20,
    rating: "4.1",
    category: "topwear",
    subcategory: "Shirts",
    theme: "formal",
    size: ["L"],
    color: ["White", "Blue"],
    image: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400"]
  },
  {
    title: "Dress",
    description: "Elegant evening dress for women.",
    brand: "Zara",
    gender: "Women",
    price: 1599,
    discount: 60,
    rating: "4.8",
    category: "ethnic",
    subcategory: "Dresses",
    theme: "party",
    size: ["S", "M", "L"],
    color: ["Red", "Black"],
    image: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400"]
  },
  {
    title: "Kurta",
    description: "Traditional kurta for women.",
    brand: "Zara",
    gender: "Women",
    price: 999,
    discount: 20,
    rating: "4.6",
    category: "ethnic",
    subcategory: "Kurtas",
    theme: "traditional",
    size: ["L"],
    color: ["Blue", "Green"],
    image: ["https://images.unsplash.com/photo-1521334884684-d80222895322?w=400"]
  },
  {
    title: "Jeans",
    description: "Stylish jeans for unisex.",
    brand: "Levi's",
    gender: "Unisex",
    price: 1099,
    discount: 50,
    rating: "4.0",
    category: "bottomwear",
    subcategory: "Jeans",
    theme: "casual",
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    image: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=400"]
  },
  {
    title: "Classic Fit Jeans",
    description: "Comfortable and stylish jeans for men.",
    brand: "Levi's",
    gender: "Men",
    category: "Bottoms",
    subcategory: "Jeans",
    price: 59.99,
    discount: 15,
    rating: "4.2",
    theme: "Streetwear",
    size: ["L"],
    color: ["Blue"],
    image: [
      "https://cdn.builder.io/api/v1/image/assets/70ad6d2d96f744648798836a6706b9db/323635352eed4542ef83c5e9d41e0f884d43499e?placeholderIfAbsent=true"
    ]
  },
  {
    title: "Classic Fit Jeans",
    description: "Comfortable and stylish jeans for men.",
    brand: "Levi's",
    gender: "Men",
    category: "Bottoms",
    subcategory: "Jeans",
    price: 59.99,
    discount: 15,
    rating: "4.2",
    theme: "Streetwear",
    size: ["L"],
    color: ["Blue"],
    image: [
      "https://cdn.builder.io/api/v1/image/assets/70ad6d2d96f744648798836a6706b9db/eb643d7fe0ae4338ccb6e5788c39e2bcd9311740?placeholderIfAbsent=true"
    ]
  }
];

module.exports = data;
